### ISSUE TITLE
IEC calls

### ISSUE THREAD

**Issue by polluks** [davervw/c64-io_monitor#11]
"I'd like to see it do the low level IEC calls, but the Kernal doesn't use the vectors."
https://github.com/jkotlinski/durexforth/discussions/388#discussioncomment-1870991

**Comment by Whammo** [comment]
I think that if I stumble upon some code that calls TALK, UNTALK, and etc. it will log them.

**Comment by davervw** [comment]
I'm absolutely interested in the low level IEC calls too, but maybe in another utility, or incarnation (another branch?).   But maybe not in the current phase of development.   Also interested in general IEC analyzer from the outside too (arduino, etc.)  Punting on this for now.
