### ISSUE TITLE
low level IEC routines

### ISSUE THREAD

**Issue by Whammo** [davervw/c64-io_monitor#5]
There is much going on down there not being logged.
 Possibly more interesting/relevant than the high level stuff.
  TALK, UNTALK, LISTEN, UNLISTEN, ACPTR, CIOUT.

**Comment by davervw** [comment]
That stuff is hooked, and should be caught if called through the KERNAL jump table.  Only, only through the jump table at end of KERNAL ROM.  But if anybody calls the vectors directly, or underlying internal entry points, then that doesn't get logged, like discovering SUPERMON64 wasn't logging anything for LOAD/SAVE.   So duplicate issue, with detail of why.
