### ISSUE TITLE
Place in memory as high as possible

### ISSUE THREAD

**Issue by Whammo** [davervw/c64-io_monitor#8]
For non-BASIC users, contiguous RAM from $A000 to start for log, or room for another binary that loads to $C000.

**Comment by davervw** [comment]
Would require implementing relocation and is not automated with the development tools I am using (to my knowledge).   I've manually created relocation tables in the past, but doing so for a moving target (code in flux) would not be fun.   But I see that logging avoiding common RAM usage would also be also a good idea.  REU anyone?

Workaround is to manually modify source to one-off a location change for the user's circumstances.   

Punting on this for now.
